#!/bin/sh -e

FILES=$(dirname $(mktemp -u))/$(basename ${PWD})-files

if test $(uname) = "Linux"; then
    os_type="linux"
elif test $(uname) = "Darwin"; then
    os_type="bsd"
fi

file_mtime() {
    if test "$os_type" = "linux"; then
        stat -c %Y $1
    elif test "$os_type" = "bsd"; then
        stat -f %m $1
    fi
}

file_list() {
    find ${PWD} -type f -name "*.*" -not -regex "^.*/\..*$"
}

list_files() {
    >$FILES
    for f in $(file_list); do
        echo "$f=$(file_mtime $f)" >> $FILES
    done
}

update_files() {
    if test "$old_mtime" = ""; then
        echo "$f=$new_mtime" >> $FILES
    elif test "$os_type" = "bsd"; then
        sed -i '' "s|$f=$old_mtime|$f=$new_mtime|" $FILES
    else
        sed -i "s|$f=$old_mtime|$f=$new_mtime|" $FILES
    fi
}

files_changed() {
    for f in $(file_list); do
        if test ! -e $f; then
            continue
        fi
        new_mtime=$(file_mtime $f)
        old_mtime=$(grep "$f=[0-9]\+" $FILES | awk -F'=' '{print $2}')
        if test "$new_mtime" != "$old_mtime"; then
            echo $f
            update_files
        fi
    done
}

spawn_child() {
    $* & child=$!
    echo "\033[31;32mChild PID: $!\033[0m"
}

kill_proc() {
    counter=0
    while kill -0 $1 2>/dev/null; do
        echo "\033[31;32mKilling $1\033[0m"
        if test "$(pgrep -P $1)" != ""; then
            echo "\033[31;33m$1 has children $(pgrep -P $1)\033[0m"
            for p in $(pgrep -P $1); do
                kill_proc $p
            done
        else
            if test "$counter" -gt 30; then
                kill -9 $1
            fi
            kill -s INT $1
            counter=$((counter + 1))
        fi
        sleep 1
    done
}

if test "$*" = ""; then
    echo "Usage: $0 <command> <args>"
    exit 2
fi

list_files

spawn_child "$*"

trap "kill_proc $child; exit 0" INT TERM

while true; do
    changed=$(files_changed)
    if test "$changed" != ""; then
        echo "\033[1;32mFiles $changed changed\033[0m"
        kill_proc $child
        echo "\033[1;32mRestarting '$*'...\033[0m"
        spawn_child "$*"
    fi
    sleep 1
done
